# Generated by Django 6.0 on 2026-01-06 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "db_table": "cities",
                "ordering": ["id"],
            },
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "super_admin"),
                    ("city_admin", "city_admin"),
                    ("analyst", "analyst"),
                    ("viewer", "viewer"),
                ],
                default="viewer",
            ),
        ),
    ]
