# Generated by Django 6.0 on 2026-01-06 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persist", "0002_citymodel_alter_usermodel_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="city_id",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="persist.citymodel",
            ),
        ),
        migrations.CreateModel(
            name="FacilityModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("school", "School"),
                            ("police", "Police"),
                            ("park", "Park"),
                        ],
                        max_length=100,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="persist.citymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "db_table": "facilities",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TrafficIncidentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("incident_type", models.CharField(max_length=100)),
                ("severity", models.IntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="persist.citymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traffic Incident",
                "verbose_name_plural": "Traffic Incidents",
                "db_table": "traffic_incidents",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AirQualityMetricModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                ("pm25", models.FloatField()),
                ("pm10", models.FloatField()),
                ("no2", models.FloatField()),
                ("o3", models.FloatField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="persist.citymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Air Quality Metric",
                "verbose_name_plural": "Air Quality Metrics",
                "db_table": "air_quality_metrics",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["city", "recorded_at"],
                        name="air_quality_city_id_829a5b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PopulationRecordModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("population", models.IntegerField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="persist.citymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Population Record",
                "verbose_name_plural": "Population Records",
                "db_table": "population_records",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["city", "date"], name="population__city_id_c297cd_idx"
                    )
                ],
            },
        ),
    ]
