# Generated by Django 6.0 on 2026-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persist", "0003_remove_usermodel_city_id_usermodel_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitymodel",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("hospital", "HOSPITAL"),
                    ("school", "SCHOOL"),
                    ("police", "POLICE"),
                    ("fire_station", "FIRE_STATION"),
                    ("park", "PARK"),
                    ("library", "LIBRARY"),
                    ("metro_station", "METRO_STATION"),
                ]
            ),
        ),
    ]
